name: $(Rev:r)
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      $buildId = $env:BUILD_BUILDNUMBER.PadLeft(7, '0');
      $versionSuffixPR = "ci-$buildId-pr$($env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)";
      $branchName = "$env:BUILD_SOURCEBRANCHNAME".Replace("_","");
      $versionSuffixBRANCH = "ci-$buildId";
      $isTag = "$env:BUILD_SOURCEBRANCH".StartsWith('refs/tags/');
      $isPR = "$env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" -ne ""
      $versionSuffix = if ($isTag) { "" } else { if ($isPR) { $versionSuffixPR } else { $versionSuffixBRANCH } };
      Write-Host "##vso[task.setvariable variable=VersionSuffix]$versionSuffix";
  - script: build.cmd -t Nuget
    displayName: Create package
    env:
      VersionSuffix: '$(VersionSuffix)'
  - script: build.cmd -t RunTests
    displayName: Run tests
    env:
      VersionSuffix: '$(VersionSuffix)'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin'
      artifactName: 'nupkgs'
  - task: NuGetCommand@2
    condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'Jet-MyGet'
      versioningScheme: byEnvVar
      versionEnvVar: Version
      packagesToPush: _none
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: bash build.sh -t Nuget
    displayName: Create package
  - script: bash build.sh -t RunTests
    displayName: Run tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
- job: MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: bash build.sh -t Nuget
    displayName: Create package
  - script: bash build.sh -t RunTests
    displayName: Run tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
